### ISSUE TITLE
Issue with parsing URLS

### ISSUE THREAD

**Issue by brenapp** [MayorMonty/minify_css#3]
Testing the tokenizer on Bootstrap, and ran into an issue tokenizing the following CSS

```CSS
@font-face {
  font-family: "Glyphicons Halflings";
  src: url(../fonts/glyphicons-halflings-regular.eot);
  src: url(../fonts/glyphicons-halflings-regular.eot?#iefix)
      format("embedded-opentype"),
    url(../fonts/glyphicons-halflings-regular.woff2) format("woff2"),
    url(../fonts/glyphicons-halflings-regular.woff) format("woff"),
    url(../fonts/glyphicons-halflings-regular.ttf) format("truetype"),
    url(../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular)
      format("svg");
}
```

Specifically, the issue comes when parsing the section `url(../fonts/glyphicons-halflings-regular.eot);`, the code loops in the Bad URL remnant recovery process. I assume this means the `)` token is being obscured somewhere
